apply plugin: 'signing'

if (ii_generateCoreJar == 'true')
{
	tasks.register('signCoreJar') {
		group 'signing'

		onlyIf {
			hasKeyStore()
		}

		outputs.upToDateWhen { false }

		dependsOn reobfCoreJar

		doLast {
			def signdir = new File("$buildDir/libs")
			signdir.mkdirs()
			ant.signjar(
					destDir: "${signdir.absolutePath}",
					jar: 'build/libs/*-core.jar',
					alias: project.ksalias ?: System.getenv("SIGN_ALIAS"),
					storetype: "pkcs12",
					keystore: project.keystore ?: System.getenv("SIGN_KEYSTORE"),
					storepass: project.storepass ?: System.getenv("SIGN_STOREPASS"),
					verbose: true,
					preservelastmodified: "true",
					tsaurl: project.timestamp_url ?: System.getenv("SIGN_TIMESTAMP")
			)
		}
	}

	tasks.coreJar.finalizedBy() {
		signCoreJar
	}
}

tasks.register('signMainJar') {
	group 'signing'
	onlyIf {
		hasKeyStore()
	}

	outputs.upToDateWhen { false }

	dependsOn reobfJar

	doLast {
		def signdir = new File("$buildDir/libs")
		signdir.mkdirs()
		ant.signjar(
				destDir: "${signdir.absolutePath}",
				jar: 'build/libs/*.jar',
				alias: project.ksalias ?: System.getenv("SIGN_ALIAS"),
				storetype: "pkcs12",
				keystore: project.keystore ?: System.getenv("SIGN_KEYSTORE"),
				storepass: project.storepass ?: System.getenv("SIGN_STOREPASS"),
				verbose: true,
				preservelastmodified: "true",
				tsaurl: project.timestamp_url ?: System.getenv("SIGN_TIMESTAMP")
		)
	}
}

boolean hasKeyStore()
{
	if (!ii_enableSigning.asBoolean()) return false
	def keystore = getOr("SIGNING_KEY_STORE_PATH", project.keystore)
	if (keystore instanceof File)
	{
		return ((File) keystore).exists()
	}
	else
	{
		return !((String) keystore).isEmpty()
	}
}