package pl.pabilo8.immersiveintelligence.common;

import blusunrize.immersiveengineering.api.crafting.IngredientStack;
import blusunrize.immersiveengineering.common.Config;
import blusunrize.immersiveengineering.common.Config.Mapped;
import blusunrize.immersiveengineering.common.Config.SubConfig;
import com.google.common.collect.Maps;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.config.Config.*;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import pl.pabilo8.immersiveintelligence.ImmersiveIntelligence;
import pl.pabilo8.immersiveintelligence.common.IIConfigHandler.IIConfig.Machines.RadioStation;
import pl.pabilo8.immersiveintelligence.common.IIConfigHandler.IIConfig.Machines.Sawmill;
import pl.pabilo8.immersiveintelligence.common.IIConfigHandler.IIConfig.Tools;
import pl.pabilo8.immersiveintelligence.common.compat.IICompatModule;
import pl.pabilo8.immersiveintelligence.common.item.tools.ItemIIMineDetector;
import pl.pabilo8.immersiveintelligence.common.util.IIStringUtil;
import pl.pabilo8.immersiveintelligence.common.util.easynbt.EasyNBT;
import pl.pabilo8.immersiveintelligence.common.world.IIWorldGen;

import java.util.Map;

/**
 * @author Pabilo8 (pabilo@iiteam.net)
 * @author Avalon (avalon@iiteam.net)
 * @updated 3.07.2025
 * @since 12.05.2019
 */
@Mod.EventBusSubscriber
public class IIConfigHandler
{
	public static final String GEARS = "Gears: Copper, Brass, Iron, Steel, Tungsten";
	public static final String BELTS = "Belts: Cloth, Steel, Rubber";

	@SubscribeEvent
	public static void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent ev)
	{
		putConfigValues();

		if(ev.getModID().equals(ImmersiveIntelligence.MODID))
		{
			ConfigManager.sync(ImmersiveIntelligence.MODID, Type.INSTANCE);
			onConfigUpdate();
		}
	}

	public static void onConfigUpdate()
	{
		ItemIIMineDetector.detectableBlocks.clear();
		for(String s : Tools.mineDetectorWhitelist)
			if(s.startsWith("oreDict:"))
				ItemIIMineDetector.detectableBlocks.add(new IngredientStack(s.replace("oreDict:", "")));
			else
			{
				String[] args = s.split(":");
				ItemStack stack = new ItemStack(EasyNBT.newNBT()
						.withString("id", args[0]+":"+args[1])
						.withInt("Count", 1)
						.conditionally(args.length > 2, nbt -> nbt.withInt("Damage", IIStringUtil.parseInt(args[2])))
						.unwrap());
				ItemIIMineDetector.detectableBlocks.add(new IngredientStack(stack));
			}
	}

	public static void putConfigValues()
	{
		Config.manual_bool.put("petroleumHere", false);
		Config.manual_bool.put("baublesHere", false);
		Config.manual_int.put("radio_station_range", RadioStation.radioRange);
		Config.manual_double.put("sawmill_gearbox_efficiency", (double)Sawmill.gearboxUpgradeEfficiency);
		Config.validateAndMapValues(IIConfig.class);
	}

	@net.minecraftforge.common.config.Config(modid = ImmersiveIntelligence.MODID)
	public static class IIConfig
	{
		@SubConfig
		@LangKey("ii.config.Graphics")
		@Comment("Customize II 3d model display, AMT, particle effects and camera options.")
		public static Graphics graphics;
		@SubConfig
		@LangKey("ii.config.Ores")
		@Comment("Customize the ore generated by II within your world.")
		public static Ores ores;
		@SubConfig
		@LangKey("ii.config.Machines")
		@Comment("Customize II machine attributes, such as speed, sound, capacity and resource usage.")
		public static Machines machines;
		@SubConfig
		@LangKey("ii.config.MechanicalDevices")
		@Comment("Customize II Mechanical devices, such as torque, speed and conversion ratios.")
		public static MechanicalDevices mechanicalDevices;
		@SubConfig
		@LangKey("ii.config.Tools")
		@Comment("Customize II handheld tools, such as energy capacity, usage and durability.")
		public static Tools tools;
		@SubConfig
		@LangKey("ii.config.Weapons")
		@Comment("Customize II's arsenal of weapons, from multi blocks to handhelds.")
		public static Weapons weapons;
		@SubConfig
		@LangKey("ii.config.Wires")
		@Comment("Customize II wires, such as length and color.")
		public static Wires wires;
		@SubConfig
		@LangKey("ii.config.Vehicles")
		@Comment("Customize II's vehicles, such as durability, speed, resource consumption and fire rate.")
		public static Vehicles vehicles;
		@SubConfig
		@LangKey("ii.config.Factions")
		@Comment("Customize II's multiplayer factions and property ownership system.")
		public static Factions factions;

		@Comment({"A list of all mods that II has integrated compatability for", "Setting any of these to false disables the respective compat"})
		public static Map<String, Boolean> compat = Maps.newHashMap(Maps.toMap(IICompatModule.moduleClasses.keySet(), (s) -> Boolean.TRUE));

		@Comment({"The maximum frequency for basic radios."})
		public static int radioBasicMaxFrequency = 32;

		@Comment({"The maximum frequency for advanced radios."})
		@LangKey("Wires")
		public static int radioAdvancedMaxFrequency = 256;

		@Comment({"Whether basic circuits should be produced in II or IE way"})
		@RequiresMcRestart
		public static boolean changeCircuitProduction = true;

		@Comment({"Whether the IE revolver should be a Early Engineering-tier weapon"})
		public static boolean changeRevolverProduction = true;

		@Comment({"Whether the the railgun should require a gun stock instead of a grip to be constructed"})
		public static boolean changeRailgunProduction = true;

		@Comment({"Whether the the chemthrower should require a gun stock instead of a grip to be constructed"})
		public static boolean changeChemthrowerProduction = true;

		@Comment({"Whether Tungsten should be smeltable in the vanilla furnace"})
		@RequiresMcRestart
		public static boolean smeltableTungsten = false;

		@Comment({"Whether Advanced Electronic Alloy should be smeltable in the vanilla furnace"})
		@RequiresMcRestart
		public static boolean smeltableAEA = false;

		@Comment({"Whether Immersive Engineering liquid concrete behavior should be replaced by II."})
		@RequiresMcRestart
		public static boolean concreteOverride = true;

		@Comment({"If disabled, II will not make any changes to IE villager trades."})
		public static boolean enableTradeOverride = true;

		@Comment({"A list of all entities for which a fakeplayer should be used when shooter is not a player"})
		public static String[] bulletFakeplayerWhitelist = new String[]{
				"minecraft:ender_dragon"
		};

		@Comment({"A list of biomes that cannot be turned into a wasteland"})
		public static String[] wastelandBiomeBlacklist = new String[]{
				"minecraft:sky",
				"minecraft:hell"
		};

		@Comment({"Whether the II Creative Tab should be divided into sub-tabs (Australian Tabs(tm))."})
		@RequiresMcRestart
		public static boolean australianCreativeTabs = true;

		public static class Graphics
		{
			@Comment({"Enable vehicle and equipment passenger animations by changing the passengers' entity model part angles."})
			public static boolean passengerAnimations = true;

			@Comment({"Enable vehicle debug overlay, showing hitboxes, motion vector arrows and individual part names."})
			public static boolean vehicleDebugOverlay = false;

			@Comment({"Enable Tactile AMT - dynamic collision boxes for multiblocks that use animations for positioning them."})
			public static boolean tactileAMT = true;

			@Comment({"Whether gun recoil is visible in first-person view."})
			public static boolean cameraRecoil = true;

			@Comment({"Whether screen shake effect should be displayed."})
			public static boolean cameraScreenShake = true;

			@Comment({"Enable camera roll motion."})
			public static boolean cameraRoll = false;

			@Comment({"Determines how hand animations should be displayed on II models",
					"0 - disabled",
					"1 - first person only",
					"2 - 1st and 3rd person (may be incompatible with mods modifying the player model)"})
			@RangeInt(min = 0, max = 2)
			public static int AMTHandDisplayMode = 1;

			@RequiresMcRestart
			@Comment({"Max amount of block penetrations that will be rendered. 0 will disable rendering."})
			public static int maxPenetratedBlocks = 64;

			@Comment({"Furthest distance II explosion effects should be visible at."})
			public static int explosionMessageDistance = 256;

			@RangeInt(min = 0)
			@Comment({"Max amount of particles that can exist within the particle system."})
			public static int maxAllowedParticles = 20000;

			@RangeInt(min = 0)
			@Comment({"Max amount of particles that will be simulated."})
			public static int maxSimulatedParticles = 6000;

			@RangeInt(min = 0)
			@Comment({"Max amount of particles that will be drawn. Should be less or equal to maxSimulatedParticles."})
			public static int maxDrawnParticles = 1000;

			@Comment({"Determines how look of II explosion particles",
					"0 - vanilla",
					"1 - vanilla enhanced with block particles",
					"2 - overhauled",
					"3 - overhauled + debris"
			})
			@RangeInt(min = 0, max = 3)
			public static int explosionParticlesStyle = 3;

			@RangeInt(min = 8, max = 256)
			public static int dynamiclyColoredTextureVariants = 64;
		}

		public static class Ores
		{
			@Comment({"A blacklist of dimensions in which IE ores won't spawn. By default this is Nether (-1) and End (1)"})
			public static int[] oreDimBlacklistNormal = new int[]{-1, 1};

			@Comment({"A blacklist of dimensions in which IE ores won't spawn. By default this is the Overworld (0) and End (1)"})
			public static int[] oreDimBlacklistNether = new int[]{0, 1};

			@Comment({"Set this to false to disable the logging of the chunks that were flagged for retrogen."})
			public static boolean retrogenLogFlagChunk = true;

			@Comment({"Set this to false to disable the logging of the chunks that are still left to retrogen."})
			public static boolean retrogenLogRemaining = true;

			@Comment({"The retrogeneration key. Basically IE checks if this key is saved in the chunks data. If it isn't, it will perform retrogen on all ores marked for retrogen.", "Change this in combination with the retrogen booleans to regen only some of the ores."})
			public static String retrogenKey = "DEFAULT_II";

			@Comment({"Generation config for Platinum Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] orePlatinum = new int[]{6, 0, 10, 2, 75};

			@Comment({"Generation config for Zinc Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] oreZinc = new int[]{10, 35, 95, 2, 100};

			@Comment({"Generation config for Tungsten Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] oreTungsten = new int[]{6, 0, 35, 2, 75};

			@Comment({"Generation config for Salt Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] oreSalt = new int[]{12, 55, 95, 1, 75};

			@Comment({"Generation config for Fluorite Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] oreFluorite = new int[]{6, 1, 55, 1, 65};

			@Comment({"Generation config for Fluorite Ore.", "Parameters: Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation"})
			@RequiresMcRestart
			@Mapped(mapClass = Config.class, mapName = "manual_intA")
			public static int[] orePhosphorus = new int[]{12, 1, 55, 1, 80};

			@Comment({"Set this to true to allow retro-generation of Platinum Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenPlatinum = false;

			@Comment({"Set this to true to allow retro-generation of Zinc Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenZinc = false;

			@Comment({"Set this to true to allow retro-generation of Tungsten Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenTungsten = false;

			@Comment({"Set this to true to allow retro-generation of Salt Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenSalt = false;

			@Comment({"Set this to true to allow retro-generation of Salt Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenFluorite = false;

			@Comment({"Set this to true to allow retro-generation of Salt Ore."})
			@RequiresMcRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean retrogenPhosphorus = false;

			@Comment({"Whether rubber trees should be generated."})
			@RequiresWorldRestart
			@Mapped(mapClass = IIWorldGen.class, mapName = "retrogenMap")
			public static boolean genRubberTrees = true;

			@RangeInt(min = 0, max = 100)
			@RequiresWorldRestart
			public static int genRubberTreesChance = 15;
		}

		public static class Tools
		{
			@SubConfig
			@LangKey("item.immersiveintelligence.skycrate_mount.mechanical.name")
			@Comment("Config for Skycrate Mounts, allows for changes to speed multipliers and energy consumption")
			public static SkycrateMounts skycrateMounts;

			@SubConfig
			@LangKey("entity.tripod_periscope.name")
			@Comment("Config for the Tripod Periscope, allows for changes to zoom, movement speed and setup time")
			public static TripodPeriscope tripodPeriscope;

			@Comment({"When enabled, drill heads will offset the dig area center when digging horizontally."})
			public static boolean drillHeadsOffset = true;

			@Comment({"A modifier to apply to the ammunition resupply time of the Ammunition Crate (weapons reload)."})
			public static float ammunitionCrateResupplyTime = 1.0f;

			@Comment({"The Lighter fuel capacity in milibuckets (mB)."})
			@RequiresMcRestart
			public static int lighterCapacity = 1000;

			@Comment({"The capacity of the measuring cup (mB)."})
			@RequiresMcRestart
			public static int measuringCupCapacity = 500;

			@Comment({"The energy capacity of the electric hammer in RF... i mean IF... i mean FE... that thing o' powerin'!."})
			@RequiresMcRestart
			public static int electricHammerCapacity = 24000;

			@Comment({"The energy capacity of the electric wirecutter."})
			@RequiresMcRestart
			public static int electricWirecutterCapacity = 24000;

			@Comment({"The energy capacity of the electric wrench."})
			@RequiresMcRestart
			public static int electricWrenchCapacity = 24000;

			//Soon?
			@Comment({"The energy capacity of the electric multitool. (when it will be added)"})
			@RequiresMcRestart
			public static int electricMultitoolCapacity = 100000;

			@Comment({"The energy usage of the electric hammer (when mining, rotating, etc. )."})
			@RequiresMcRestart
			public static int electricHammerEnergyPerUse = 100;

			@Comment({"The energy usage of the electric hammer when building advanced multiblocks (per tick)."})
			@RequiresMcRestart
			public static int electricHammerEnergyPerUseConstruction = 4096;

			@Comment({"The energy usage of the electric wirecutter (when cutting wires)."})
			@RequiresMcRestart
			public static int electricWirecutterEnergyPerUse = 100;

			@Comment({"The energy usage of the electric wrench (when destroying blocks / upgrading)."})
			@RequiresMcRestart
			public static int electricWrenchEnergyPerUse = 4000;

			@Comment({"The upgrade progress added per use of the engineer's wrench (default 1IF=1 Point of Progress™)."})
			@RequiresMcRestart
			public static int electricWrenchUpgradeProgress = 4000;

			@Comment({"The durability of the engineer's wrench."})
			@RequiresMcRestart
			public static int wrenchDurability = 128;

			@Comment({"The upgrade progress added per use of the engineer's wrench."})
			@RequiresMcRestart
			public static int wrenchUpgradeProgress = 1000;

			@Comment({"Max zoom of the binoculars (in Blu's Unit of Magnification Measurement™)."})
			@RequiresMcRestart
			public static float[] binocularsMaxZoom = new float[]{0.1f, 0.125f, 0.167f, 0.25f, 0.5f};

			@Comment({"Max zoom of the advanced binoculars (in Blu's Unit of Magnification Measurement™)."})
			@RequiresMcRestart
			public static float[] advancedBinocularsMaxZoom = new float[]{0.05f, 0.0625f, 0.0833f, 0.1f, 0.25f, 0.5f};

			@Comment({"The energy capacity of advanced binoculars (when using Infrared Sight)."})
			@RequiresMcRestart
			public static int advancedBinocularsEnergyCapacity = 4000;

			@Comment({"The energy usage of advanced binoculars (when using Infrared Sight)."})
			@RequiresMcRestart
			public static int advancedBinocularsEnergyUsage = 150;

			@Comment({"A list of blocks that the Mine Detector will detect (in addition to mines).",
					"Use the format 'modid:blockname:meta', e.g. 'minecraft:diamond_ore:0', or oreDict:ore_name for ore dictionary entries.",
					"Leave empty to disable."})
			public static String[] mineDetectorWhitelist = new String[]{
					"immersiveintelligence:tellermine",
					"immersiveintelligence:tripmine",
					"minecraft:iron_door",
					"minecraft:iron_trapdoor",
					"oreDict:blockIron",
					"oreDict:blockSheetmetalIron",
					"oreDict:slabSheetmetalIron",
					"oreDict:blockSteel",
					"oreDict:blockSheetmetalSteel",
					"oreDict:slabSheetmetalSteel",
					"oreDict:scaffoldingSteel",
					"immersiveintelligence:metal_device:0",
					"immersiveintelligence:small_crate:3",
					"immersiveintelligence:small_crate:4",
					"immersiveintelligence:small_crate:5"
			};

			@Comment({"The detection radius (technically a square) of the Mine Detector (in blocks)."})
			public static int mineDetectorRadius = 4;

			//Durability


			@Comment({"The durability (max number of uses) of the Precision Buzzsaw."})
			@RequiresMcRestart
			public static int precisionToolBuzzsawDurability = 150;

			@Comment({"The durability (max number of uses) of the Precision Drill."})
			@RequiresMcRestart
			public static int precisionToolDrillDurability = 250;

			@Comment({"The durability (max number of uses) of the Precision Inserter."})
			@RequiresMcRestart
			public static int precisionToolInserterDurability = 200;

			@Comment({"The durability (max number of uses) of the Precision Solderer."})
			@RequiresMcRestart
			public static int precisionToolSoldererDurability = 150;

			@Comment({"The durability (max number of uses) of the Precision Welder."})
			@RequiresMcRestart
			public static int precisionToolWelderDurability = 250;

			@Comment({"The durability (max number of uses) of the Precision Hammer."})
			@RequiresMcRestart
			public static int precisionToolHammerDurability = 200;

			@Comment({"The durability (max number of uses) of the Iron Sawblade."})
			@RequiresMcRestart
			public static int sawbladeIronDurability = 150;

			@Comment({"The durability (max number of uses) of the Steel Sawblade."})
			@RequiresMcRestart
			public static int sawbladeSteelDurability = 300;

			@Comment({"The durability (max number of uses) of the Tungsten Sawblade."})
			@RequiresMcRestart
			public static int sawbladeTungstenDurability = 550;

			//Usage Time

			@Comment({"The usage time of the Precision Buzzsaw."})
			@RequiresMcRestart
			public static int precisionToolBuzzsawUsageTime = 100;

			@Comment({"The usage time of the Precision Drill."})
			@RequiresMcRestart
			public static int precisionToolDrillUsageTime = 100;

			@Comment({"The usage time of the Precision Inserter."})
			@RequiresMcRestart
			public static int precisionToolInserterUsageTime = 0;

			@Comment({"The usage time of the Precision Solderer."})
			@RequiresMcRestart
			public static int precisionToolSoldererUsageTime = 80;

			@Comment({"The usage time of the Precision Welder."})
			@RequiresMcRestart
			public static int precisionToolWelderUsageTime = 100;

			@Comment({"The usage time of the Precision Hammer."})
			@RequiresMcRestart
			public static int precisionToolHammerUsageTime = 80;

			@Comment({"The capacity of the Improved Capacitor Backpack (in IF)."})
			@RequiresMcRestart
			public static int advancedPowerpackCapacity = 1000000;

			@Comment({"Whether advanced multiblock construction should be free and instantenous in creative mode."})
			public static boolean instantCreativeConstruction = true;
			@Comment({"Whether machine upgrading should be free and instantenous in creative mode."})
			public static boolean instantCreativeUpgrading = true;

			public static class SkycrateMounts
			{
				@Comment({"The speed of the Mechanical Skycrate Mount."})
				@RequiresMcRestart
				public static float mechSpeed = 0.25f;

				@Comment({"The energy (max distance to be traveled) of the Mechanical Skycrate Mount."})
				@RequiresMcRestart
				public static float mechEnergy = 35;

				@Comment({"The speed of the Electric Skycrate Mount."})
				@RequiresMcRestart
				public static float electricSpeed = 1f;

				@Comment({"The energy to distance ratio of the Electric Skycrate Mount. (in Immersive Flux per Meter)"})
				@RequiresMcRestart
				public static int electricEnergyRatio = 128;

				@Comment({"The energy capacity of the Electric Skycrate Mount (in Immersive Flux)."})
				@RequiresMcRestart
				public static float electricEnergy = 55;

			}

			public static class TripodPeriscope
			{
				@Comment({"Determines how fast the Tripod Periscope can be set up (in ticks)."})
				@RangeInt(min = 0)
				@RequiresMcRestart
				public static int setupTime = 60;

				@Comment({"The yaw turn speed of the Tripod Periscope (in degrees)."})
				@RequiresMcRestart
				public static float turnSpeed = 2.5f;

				@Comment({"Max zoom of a machinegun with a scope mounted (in Blu's Unit of Distance Measurement™)."})
				@RequiresMcRestart
				public static float[] tripodZoomSteps = new float[]{0.01f, 0.02f, 0.04f, 0.0625f, 0.0833f, 0.125f, 0.25f, 0.5f};
			}
		}

		public static class Machines
		{
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_device.latex_collector.name")
			@Comment("Config for the Latex Collector, adjusts the time till completion")
			public static LatexCollector latexCollector;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.radio_station.name")
			@Comment("Config for the Radio Station, allows for changes to energy storage, energy usage, range, and weather impact")
			public static RadioStation radioStation;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.data_input_machine.name")
			@Comment("Config for the Data Input Machine, allows for changes to energy usage, storage and production time")
			public static DataInputMachine dataInputMachine;
			@SubConfig
			@LangKey("desc.immersiveengineering.info.multiblock.II:ArithmeticLogicMachine")
			@Comment("Config for the Arithmetic-Logic machine, allows for changes to energy usage and capacity")
			public static ArithmeticLogicMachine arithmeticLogicMachine;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.printing_press.name")
			@Comment("Config for the Printing Press, allows for changes to ink usage, print time, energy storage and capacity")
			public static PrintingPress printingPress;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.chemical_bath.name")
			@Comment("Config for the Chemical Bath, allows for changes to energy and fluid capacity")
			public static ChemicalBath chemicalBath;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.electrolyzer.name")
			@Comment("Config for the Electrolyzer, allows for changes to the energy and fluid capacity")
			public static Electrolyzer electrolyzer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.precision_assembler.name")
			@Comment("Config for the precision Assembler, allows changes to energy capacity and processing time")
			public static PrecisionAssembler precisionAssembler;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock1.coagulator.name")
			@Comment("Config for the Coagulator, allows for changes to processing time, energy and fluid capacity")
			public static Coagulator coagulator;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock1.vulcanizer.name")
			@Comment("Config for the Vulcanize, allows for changes to energy capacity")
			public static Vulcanizer vulcanizer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.artillery_howitzer.name")
			@Comment("Config for the Artillery Howitzer, allows for changes to animation times, movement speed, energy usage and capacity")
			public static ArtilleryHowitzer artilleryHowitzer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.ballistic_computer.name")
			@Comment("Config for the Ballistic Computer, allows for changes to energy usage and capacity")
			public static BallisticComputer ballisticComputer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.missile_silo.name")
			@Comment("Config for the Missile Silo, allows for changes to energy capacity")
			public static MissileSilo missileSilo;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.scanning_conveyor.name")
			@Comment("Config for the Scanning Conveyer, allows for changes to energy capacity and usage")
			public static ScanningConveyor scanningConveyor;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.inserter.name")
			@Comment("Config for the Inserter, allows for changes to processing speed, maximum extraction amount, energy capacity and usage")
			public static Inserter inserter;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.advanced_inserter.name")
			@Comment("Config for the Advanced Inserter, allows for changes to processing speed, maximum extraction amount, energy capacity and usage")
			public static AdvancedInserter advancedInserter;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.fluid_inserter.name")
			@Comment("Config for the Fluid Inserter, allows for changes to max fluid output, energy usage and capacity")
			public static FluidInserter fluidInserter;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.advanced_fluid_inserter.name")
			@Comment("Config for the Advanced Fluid Inserter, allows for changes to max fluid output, energy usage and capacity")
			public static AdvancedFluidInserter advancedFluidInserter;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.chemical_dispenser.name")
			@Comment("Config for the Chemical Dispenser, allows for changes to movement speed, energy usage and capacity")
			public static ChemicalDispenser chemicalDispenser;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_device.small_data_buffer.name")
			@Comment("Config for the Small Data Buffer, allows changes to maximum packet capacity")
			public static SmallDataBuffer smallDataBuffer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.wooden_multiblock.skycrate_station.name")
			@Comment("Config for the Skycrate Station, allows for changes to multiblock processing time, and RPM interaction adjustments ")
			public static SkyCrateStation skycrateStation;
			@SubConfig
			@LangKey("tile.immersiveintelligence.wooden_multiblock.skycart_station.name")
			@Comment("Config for the Skycart Station, allows for changes to minecart processing time")
			public static SkyCartStation skycartStation;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock.packer.name")
			@Comment("Config for the Packer, allows for changes to processing time, energy capacity, energy usage, and fluid capacity")
			public static Packer packer;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock1.redstone_data_interface.name")
			@Comment("Abandon hope, all ye who enter")
			public static RedstoneInterface redstoneInterface;
			@SubConfig
			@LangKey("tile.immersiveintelligence.wooden_multiblock.sawmill.name")
			@Comment("Config for the Sawmill, allows for changes to RPM max/min and Torque max/min")
			public static Sawmill sawmill;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.alarm_siren.name")
			@Comment("Config for the Alarm Siren, allows for changes to default volume")
			public static AlarmSiren alarmSiren;
			@SubConfig
			@LangKey("tile.immersiveintelligence.data_connector.programmable_speaker.name")
			@Comment("Config for the Programmable Speaker, allows for changes to default volume")
			public static ProgrammableSpeaker speaker;
			@SubConfig
			@LangKey("ii.config.EffectCrates")
			@Comment("Config for the crates (Repair, Medical, etc). Allows for changes to energy capacity, fluid capacity and energy consumption per action")
			public static EffectCrates effectCrates;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock1.emplacement.name")
			@Comment("Config for Eplacements, allows for changes to energy capacity, deployment time, repair cost and repair delay.")
			public static Emplacement emplacement;
			@SubConfig
			@LangKey("tile.immersiveintelligence.metal_multiblock1.filler.name")
			@Comment("Config for the Filler, allows for changes to energy capacity and 'dust' capacity")
			public static Filler filler;
			@SubConfig
			@LangKey("desc.immersiveengineering.info.multiblock.II:VehicleWorkshop")
			@Comment("Config for the Vehicle Workshop, allows for changes to energy and fuel capacity")
			public static VehicleWorkshop vehicleWorkshop;

			public static class RedstoneInterface
			{

			}

			public static class AlarmSiren
			{
				@Comment({"The distance the siren can be heard from."})
				public static int soundRange = 16;
			}

			public static class ProgrammableSpeaker
			{
				@Comment({"The distance the speaker can be heard from."})
				public static int soundRange = 24;
			}

			public static class Filler
			{
				@Comment({"Energy capacity of the the Filler (in IF)."})
				public static int energyCapacity = 16000;

				@RequiresWorldRestart
				@Comment({"Dust capacity of the the Filler (in mB, 1 dustStack is 100mB)."})
				public static int dustCapacity = 32000;
			}

			public static class VehicleWorkshop
			{
				@Comment({"Energy capacity of the the Vehicle Workshop (in IF)."})
				public static int energyCapacity = 100000;

				@RequiresWorldRestart
				@Comment({"Fluid (diesel) capacity of the the Vehicle Workshop (in mB)."})
				public static int dieselCapacity = 24000;
			}

			public static class EffectCrates
			{
				@Comment({"The amount of fluid a Medical Crate can store (in mB)"})
				public static int mediCrateTankSize = 4000;

				@Comment({"The amount of fluid a Medical Crate uses after applying the effect (in mB)"})
				public static int mediCrateFluidDrain = 250;

				@Comment({"The amount of energy an inserter upgraded Medical Crate takes per one heal (in IF/RF/FE)"})
				public static int mediCrateEnergyPerAction = 50;

				@Comment({"The amount of energy an inserter upgraded Repair Crate takes per one repair (in IF/RF/FE)"})
				public static int repairCrateEnergyPerAction = 65;

				@Comment({"The amount of energy an inserter upgraded Ammunition Crate takes per one 4 second effect (in IF/RF/FE)"})
				public static int ammoCrateEnergyPerAction = 85;

				@Comment({"The amount of energy an inserter upgraded crate can store (in IF/RF/FE)"})
				public static int maxEnergyStored = 4000;

				@Comment({"The amount of energy an inserter upgraded crate can drain in one tick (in IF/RF/FE)"})
				public static int energyDrain = 40;
			}

			public static class Packer
			{
				@Comment({"Energy capacity of the glorious boxing device also known as The Packer."})
				public static int energyCapacity = 16000;

				@Comment({"Additional energy capacity of the packer when the charging module upgrade is present."})
				public static int energyCapacityUpgrade = 16000000;

				@Comment({"Maximum possible energy transfer per one charge action, when the charging module upgrade is present."})
				public static int energyCapacityUpgradeMaxTransfer = 4000000;

				@Comment({"Additional fluid capacity of the packer when the pump module upgrade is present."})
				public static int fluidCapacityUpgrade = 96000;

				@Comment({"Energy usage of the packer (if any stack/fluid/energy input/output is performed)."})
				public static int energyUsage = 4096;

				@Comment({"Duration of the packing process (in ticks)."})
				public static int actionTime = 260;
			}

			public static class SkyCrateStation
			{
				@Comment({"Degrees/tick required by the machine to start working."})
				public static int speedMin = 20;

				@Comment({"Degrees/tick required by the machine to work at full efficiency."})
				public static int speedEfficient = 80;

				@Comment({"Max Degrees/tick (machine will break if over)."})
				public static int speedBreaking = 240;

				@Comment({"Torque required by the machine to start working."})
				public static int torqueMin = 4;

				@Comment({"Torque required by the machine to work at full efficiency."})
				public static int torqueEfficient = 8;

				@Comment({"Max Torque (machine will break if over)."})
				public static int torqueBreaking = 256;

				@Comment({"How long does it take for the station to put a crate onto the line. (in ticks)"})
				public static int outputTime = 240;

				@Comment({"How long does it take for the station to put a crate onto a minecart. (in ticks)"})
				public static int inputTime = 240;

				@Comment({"How long does it take for the minecart to drive into the station. (in ticks)"})
				public static int crateInTime = 60;

				@Comment({"How long does it take for the minecart to drive out of the station. (in ticks)"})
				public static int crateOutTime = 60;
			}

			public static class SkyCartStation
			{
				@Comment({"How long does it take for the minecart to drive into the station. (in ticks)"})
				public static int minecartInTime = 40;

				@Comment({"How long does it take for the minecart to drive out of the station. (in ticks)"})
				public static int minecartOutTime = 40;
			}

			public static class Sawmill
			{
				@Comment({"Degrees/tick required by the machine to start working."})
				public static int speedMin = 10;

				@Comment({"Degrees/tick required by the machine to work at full efficiency."})
				public static int speedEfficient = 20;

				@Comment({"Max Degrees/tick (machine will break if over)."})
				public static int speedBreaking = 160;

				@Comment({"Torque required by the machine to start working."})
				public static int torqueMin = 4;

				@Comment({"Torque required by the machine to work at full efficiency."})
				public static int torqueEfficient = 6;

				@Comment({"Max Torque (machine will break if over)."})
				public static int torqueBreaking = 140;

				@Comment({"Degrees/tick required by the Improved Gearbox upgrade to multiply the machine's speed."})
				public static int speedGearboxUpgrade = 40;

				@Comment({"Efficiency modifier for the Improved Gearbox upgrade."})
				public static float gearboxUpgradeEfficiency = 2.5f;
			}

			public static class MechanicalPump
			{
				@Comment({"Degrees/tick required by the machine to start working."})
				public static int speedMin = 20;

				@Comment({"Degrees/tick required by the machine to work at full efficiency."})
				public static int speedEfficient = 40;

				@Comment({"Max Degrees/tick (machine will break if over)."})
				public static int speedBreaking = 160;

				@Comment({"Torque required by the machine to start working."})
				public static int torqueMin = 2;

				@Comment({"Torque required by the machine to work at full efficiency."})
				public static int torqueEfficient = 6;

				@Comment({"Max Torque (machine will break if over)."})
				public static int torqueBreaking = 40;
			}

			public static class RadioStation
			{
				@Comment({"Energy required to construct the radio station (in IF)."})
				public static int constructionEnergy = 200000;

				@Comment({"Energy capacity of the radio station (in IF)."})
				public static int energyCapacity = 32000;

				@Comment({"Energy usage when sending a signal (in IF)."})
				public static int energyUsage = 2048;

				@Comment({"Energy usage when a radio station is working."})
				public static int energyUsageIdle = 512;

				@Comment({"Range of the radio station (in which the signals can be received) in blocks from center (radius)."})
				@Mapped(mapClass = Config.class, mapName = "manual_int")
				public static int radioRange = 128;

				@RangeDouble(min = 0, max = 1)
				@Comment({"How much the range decreases when there is bad weather (rain, snow) ( 1 - full range, 0.5 - half range, 0 - no range, etc.)"})
				public static double weatherHarshness = 0.75;
			}

			public static class DataInputMachine
			{
				@Comment({"Energy capacity of the data input machine."})
				public static int energyCapacity = 16000;

				@Comment({"Energy usage when sending a signal."})
				public static int energyUsage = 2048;

				@Comment({"Energy per step of punching a tape (1/60 of the full energy needed)."})
				public static int energyUsagePunchtape = 128;

				@Comment({"Duration of tape punching process in ticks (1 tick = 1/20 Second)."})
				public static int timePunchtapeProduction = 80;
			}

			public static class ArithmeticLogicMachine
			{
				@Comment({"Energy capacity of the arithmetic-logic machine."})
				public static int energyCapacity = 24000;

				@Comment({"Energy usage of the arithmetic-logic machine per circuit."})
				public static int energyUsage = 1536;
			}

			public static class PrintingPress
			{
				@Comment({"Energy capacity of the printing press."})
				public static int energyCapacity = 24000;

				@Comment({"Energy usage of the printing press per page printed."})
				public static int energyUsage = 2048;

				@Comment({"Page printing duration (in ticks)."})
				public static int printTime = 90;

				@Comment({"Ink used per character printed (mB)."})
				public static int printInkUsage = 2;

				@Comment({"Ink used to print a Logistics Tag (mB)."})
				public static int printInkUsageLogiTag = 512;
			}

			public static class ChemicalBath
			{
				@Comment({"Energy capacity of the chemical bath."})
				public static int energyCapacity = 16000;

				@RequiresWorldRestart
				@Comment({"Fluid capacity of the chemical bath."})
				public static int fluidCapacity = 24000;
			}

			public static class ChemicalPainter
			{
				@Comment({"Energy capacity of the chemical painter."})
				public static int energyCapacity = 16000;

				@RequiresWorldRestart
				@Comment({"Fluid capacity of each tank of the chemical painter."})
				public static int fluidCapacity = 8000;
			}

			public static class Electrolyzer
			{
				@Comment({"Energy capacity of the electrolyzer."})
				public static int energyCapacity = 16000;

				@RequiresWorldRestart
				@Comment({"Fluid capacity of the electrolyzer."})
				public static int fluidCapacity = 12000;
			}

			public static class PrecisionAssembler
			{
				@Comment({"Energy capacity of the chemical bath."})
				public static int energyCapacity = 16000;

				@Comment({"Hatch opening (or closing) time (in ticks)"})
				public static int hatchTime = 40;

				@Comment({"Tool traverse time, added to beginning and end of animation (in ticks)"})
				public static int toolMoveTime = 30;
			}

			public static class ArtilleryHowitzer
			{
				@Comment({"Energy capacity of the artillery howitzer."})
				public static int energyCapacity = 4000000;

				@Comment({"Additional energy usage when moving the platform, loading or shooting."})
				public static int energyUsageActive = 1024;

				@Comment({"Passive energy usage of the howitzer (in IF)."})
				public static int energyUsagePassive = 2048;

				@Comment({"Time needed for the platform to ascend/descend (in ticks)."})
				public static int platformTime = 200;

				@Comment({"Time needed for the howitzer to fire (in ticks)."})
				public static int gunFireTime = 240;

				@RangeDouble(min = 0.0, max = 1.0)
				@Comment({"In what moment of animation should the gun fire the bullet (0.0-1.0 fraction of gunFireTime)"})
				public static double gunFireMoment = 0.5989;

				@Comment({"Time needed to open the howitzer door (in ticks)."})
				public static int doorTime = 248;

				@Comment({"How many degrees per tick can the howitzer rotate (in degrees)"})
				public static int rotateSpeed = 2;

				@Comment({"How long does it take for the howitzer to load or unload a shell to the platform shell rack (in ticks)"})
				public static int loadRackTime = 360;

				@Comment({"How long does it take for the howitzer to move the shell by one item slot using conveyor (in ticks)"})
				public static int conveyorTime = 40;

				@Comment({"How much explosion and block breaking damage the multiblock can take (in half-hearts)."})
				public static int baseHealth = 3600;
			}

			public static class BallisticComputer
			{
				@Comment({"Energy capacity of the ballistic computer."})
				public static int energyCapacity = 24000;

				@Comment({"Energy capacity of the ballistic computer."})
				public static int energyUsage = 16000;
			}

			public static class ScanningConveyor
			{
				@Comment({"Energy capacity of the scanning conveyor."})
				public static int energyCapacity = 8000;

				@Comment({"Energy usage when scanning an ItemStack."})
				public static int energyUsage = 128;
			}

			public static class MissileSilo
			{
				@Comment({"Energy capacity of the missile silo (per one block of height) (in IF)."})
				public static int energyCapacity = 2500000;
			}

			public static class Radar
			{
				@Comment({"Energy required to construct the radar (in IF)."})
				public static int constructionEnergy = 200000;

				@Comment({"Energy capacity of the radar (in IF)."})
				public static int energyCapacity = 64000;

				@Comment({"Energy usage of the radar per tick (in IF)."})
				public static int energyUsage = 2048;

				@Comment({"Radar target detection radius (in blocks)."})
				public static int detectionRadius = 72;

				@Comment({"How much explosion and block breaking damage the multiblock can take (in half-hearts)."})
				public static int baseHealth = 600;
			}

			public static class Flagpole
			{
				@Comment({"Radius for chunks to be claimed (not loaded) around this multiblock"})
				public static int chunkClaimRadius = 2;

				@Comment({"Maximum allowed radius for chunks to be loaded around this multiblock."})
				@RangeInt(min = 0, max = 12)
				public static int maxChunksLoadedRadius = 3;

				@Comment({"How much explosion and block breaking damage the multiblock can take (in half-hearts)."})
				public static int baseHealth = 800;
			}

			public static class Emplacement
			{
				@Comment({"Energy capacity of the emplacement (in IF)."})
				public static int energyCapacity = 32000;

				@Comment({"Idle energy usage per tick, regardless whether a weapon is installed or not (in IF)."})
				public static int baseEnergyUsage = 512;

				@Comment({"Time for the multiblock to open/close the lid (in ticks)."})
				public static int lidTime = 240;

				@Comment({"Radius for chunks to be claimed (not loaded) around this multiblock"})
				public static int chunkClaimRadius = 1;

				@Comment({"Interval for the multiblock weapon to update sighted targets (in ticks)."})
				public static int sightUpdateTime = 10;

				@Comment({"Energy required to perform a single repair action (in IF)."})
				public static int repairCost = 1024;

				@Comment({"Time for a single repair action (in ticks)."})
				public static int repairDelay = 40;

				@Comment({"Amount of turret health restored during single repair action (in half-hearts)."})
				public static int repairAmount = 4;

				@Comment({"How much explosion and block breaking damage the multiblock can take (in half-hearts)."})
				public static int baseHealth = 600;
			}

			public static class Inserter
			{
				@Comment({"Energy capacity of the inserter (in IF)"})
				public static int energyCapacity = 4096;
				@Comment({"Energy usage of the inserter per tick (in IF)"})
				public static int energyUsage = 128;
				@Comment({"How long does it take for the inserter to perform a task (in ticks)"})
				public static int taskTime = 20;
				@Comment({"How many items can be taken per single operation"})
				public static int maxTake = 32;
			}

			public static class AdvancedInserter
			{
				@Comment({"Energy capacity of the inserter (in IF)"})
				public static int energyCapacity = 4096;
				@Comment({"Energy usage of the inserter per tick (in IF)"})
				public static int energyUsage = 256;
				@Comment({"How long does it take for the inserter to perform a task (in ticks)"})
				public static int taskTime = 10;
				@Comment({"How many items can be taken per single operation"})
				public static int maxTake = 64;

			}

			public static class FluidInserter
			{
				@Comment({"Energy capacity of the inserter."})
				public static int energyCapacity = 2048;
				@Comment({"Energy usage of the inserter per item taken."})
				public static int energyUsage = 128;
				@Comment({"How long does it take for the inserter to perform a task (in ticks)"})
				public static int taskTime = 40;
				@Comment({"How much fluid can the inserter take per a single task (in milibuckets)"})
				public static int maxTake = 500;
				@Comment({"How much milk should the inserter extract during the cow milking task (in milibuckets)"})
				public static int cowMilkAmount = 100;
			}

			public static class AdvancedFluidInserter
			{
				@Comment({"Energy capacity of the inserter."})
				public static int energyCapacity = 4096;
				@Comment({"Energy usage of the inserter per item taken."})
				public static int energyUsage = 256;
				@Comment({"How long does it take for the inserter to perform a task (in ticks)"})
				public static int taskTime = 20;
				@Comment({"How much fluid can the inserter take per a single task (in milibuckets)"})
				public static int maxTake = 1000;
				@Comment({"How much milk should the inserter extract during the cow milking task (in milibuckets)"})
				public static int cowMilkAmount = 200;

			}

			public static class ChemicalDispenser
			{
				@Comment({"Energy capacity of the chemical dispenser."})
				public static int energyCapacity = 2048;

				@Comment({"Energy usage of the chemical dispenser per one shot."})
				public static int energyUsage = 128;

				@Comment({"How long does it take for the chemical dispenser to rotate 45 degrees horizontally (in ticks)"})
				public static int rotateHTime = 240;

				@Comment({"How long does it take for the chemical dispenser to rotate 45 degrees vertically (in ticks)"})
				public static int rotateVTime = 180;

			}

			public static class SmallDataBuffer
			{
				@Comment({"Amount of data packets the machine can store."})
				public static int packetCapacity = 4;
			}

			public static class FuelStation
			{
				@Comment({"Energy capacity of the fuel station."})
				public static int energyCapacity = 16000;

				@Comment({"Energy amount used per one mB of fluid transfered."})
				public static int energyUsage = 4;

				@Comment({"Amount of fluid transfered per tick."})
				public static int fluidTransfer = 120;

				@RequiresWorldRestart
				@Comment({"Fluid capacity of the fuel station."})
				public static int fluidCapacity = 64000;
			}

			public static class LatexCollector
			{
				@Comment({"Collection time of a single bucket (in ticks)."})
				public static int collectTime = 12000;
			}

			public static class CO2Collector
			{
				@Comment({"CO2 collection time (in ticks)."})
				public static int blastFurnaceCollectTime = 20;

				@Comment({"CO2 amount collected (in mB)."})
				public static int blastFurnaceCollectAmount = 5;

				@Comment({"CO2 collection time (in ticks)."})
				public static int fermenterCollectTime = 20;

				@Comment({"CO2 amount collected (in mB)."})
				public static int fermenterCollectAmount = 2;
			}

			public static class Vulcanizer
			{
				@Comment({"Energy capacity of the vulcanizer (in IF)."})
				public static int energyCapacity = 16000;
			}

			public static class Coagulator
			{
				@Comment({"Energy capacity of the coagulator (in IF)."})
				public static int energyCapacity = 16000;

				@Comment({"Fluid capacity of a coagulator tank (in mB)."})
				public static int fluidCapacity = 16000;

				@Comment({"Default bucket wait time for a coagulator process, when not specified in recipe (in ticks)."})
				public static int bucketTime = 2400;

				@Comment({"How long does it take to move a crane 1 block (in ticks)."})
				public static int craneMoveTime = 20;

				@Comment({"Duration of crane bucket actions (in ticks)."})
				public static int craneBucketActionTime = 100;
			}

			public static class AmmunitionAssembler
			{
				@Comment({"Energy capacity of the ammunition workshop (in IF)."})
				public static int energyCapacity = 16000;
			}

			public static class ProjectileWorkshop
			{
				@Comment({"Energy capacity of the Projectile Workshop (in IF)."})
				public static int energyCapacity = 16000;

				@Comment({"Energy usage of the Projectile Workshop during core production (in IF/t)"})
				public static int productionEnergyUsage = 50;

				@Comment({"Energy usage of the Projectile Workshop during core production (in IF/t)"})
				public static int fillingEnergyUsage = 70;

				@Comment({"Fluid capacity of a Projectile Workshop coolant (water) tank (in mB)."})
				public static int coolantTankCapacity = 6000;

				@Comment({"Fluid capacity of a Projectile Workshop fluid bullet component buffer tank (in mB)."})
				public static int componentTankCapacity = 1000;

				@Comment({"Maximum amount of bullet component stored in a Projectile Workshop (16 is default amount per one item / 1000mB of a fluid)."})
				public static int componentCapacity = 512;

				@Comment({"How long does it take to produce a projectile (in ticks, multiplied by caliber)."})
				public static int productionTime = 35;

				@Comment({"How long does it take to fill a projectile with components (in ticks, multiplied by caliber)."})
				public static int fillingTime = 35;
			}
		}

		public static class Weapons
		{
			//thanks for reminding me, trainmaniac ^^
			@Comment({"Whether blocks should be damaged when hit by bullets"})
			public static boolean blockDamage = true;

			@Comment({"Whether bullets should whistle, when flying close to player (slightly affects performance)"})
			public static boolean bulletsWhistleSound = true;
			@Comment({"Whether artillery shells should whistle, when about to impact"})
			public static boolean artilleryImpactSound = true;

			@SubConfig
			@LangKey("ii.config.Ammunition")
			@Comment("Config for Projectiles, allows for changes to projectile velocity")
			public static Ammunition ammunition;
			@SubConfig
			@LangKey("item.immersiveintelligence.submachinegun.name")
			@Comment("Config for the Submachinegun, allows for changes to reload time, aim time, recoil and enemy attract range.")
			public static Submachinegun submachinegun;
			@SubConfig
			@LangKey("item.immersiveintelligence.machinegun.name")
			@Comment("Config for the Machinegun, allows for changes to reload time, aim time, recoil, overheat and modification settings")
			public static Machinegun machinegun;
			@SubConfig
			@LangKey("item.immersiveintelligence.rifle.name")
			@Comment("Config for the Rifle, allows for changes to reload time, aim time, capacity, and recoil")
			public static Rifle rifle;
			@SubConfig
			@LangKey("item.immersiveintelligence.assault_rifle.name")
			@Comment("Config for the Assault Rifle, allows for changes to reload time, aim time, recoil, overheat and modification settings")
			public static AssaultRifle assaultRifle;
			@SubConfig
			@LangKey("item.immersiveintelligence.mortar.name")
			@Comment("Config for the Mortar, allows for changes to pitch speed, fire rate and setup time")
			public static Mortar mortar;
			@SubConfig
			@LangKey("ii.config.Emplacement_Weapons")
			@Comment("Config for Emplacement weapons, allows for the adjustment of fire rate, detection radius, movement speed and health")
			public static EmplacementWeapons emplacementWeapons;
			@SubConfig
			@LangKey("desc.immersiveintelligence.toolupgrade.item.railgun")
			@Comment("Config for the Railgun, allows for the toggling of II related features, such as recoil and penetration")
			public static Railgun railgun;
			@SubConfig
			@LangKey("ii.config.Grenade")
			@Comment("Config for Grenades, such as throwing speed")
			public static Grenade grenade;
			@SubConfig
			@LangKey("ii.config.Mines")
			@Comment("Config for Mines (and radio explosives). Allows for changes to energy capacity, useage, radio range and mob blacklists")
			public static Mines mines;
			@SubConfig
			@LangKey("ii.config.Light_Engineer_Armor")
			@Comment("Config for the Light Engineers armor. Allows for changes to upgrade energy and resource usage.")

			public static LightEngineerArmor lightEngineerArmor;

			public static class LightEngineerArmor
			{
				@Comment({"The energy usage of the Infiltrator's Headgear when IR is active (in IF / 20 ticks)."})
				@RangeInt(min = 0)
				public static int irHeadgearEnergyUsage = 150;

				@Comment({"The energy usage of the Technician's Headgear when it is active (in IF / 20 ticks)."})
				@RangeInt(min = 0)
				public static int technicianHeadgearEnergyUsage = 50;

				@Comment({"The energy usage of the Engineer's Headgear when it is active (in IF / 20 ticks)."})
				@RangeInt(min = 0)
				public static int engineerHeadgearEnergyUsage = 225;

				@Comment({"The multiplier of electric damage taken when an anti-static mesh is worn under water (in half-hearts)."})
				@RangeDouble(min = 0)
				public static double antiStaticMeshWaterDamageMod = 1.5;

				@Comment({"The energy usage of the exoskeleton when running (in IF)."})
				@RangeInt(min = 0)
				public static int exoskeletonEnergyUsage = 200;

				@Comment({"The oxygen capacity of the scuba tank (in mB)."})
				@RangeInt(min = 0)
				@RequiresMcRestart
				public static int scubaTankCapacity = 10000;

				@Comment({"The oxygen capacity of the scuba tank (in mB / 20 ticks)."})
				@RangeInt(min = 0)
				public static int scubaTankUsage = 20;

			}

			public static class Mortar
			{
				@Comment({"Determines how fast the Mortar can be set up (in ticks)."})
				@RangeInt(min = 0)
				@RequiresMcRestart
				public static int setupTime = 100;

				@Comment({"Determines how fast the Mortar can be fired (in ticks)."})
				@RangeInt(min = 0)
				@RequiresMcRestart
				public static int shootTime = 80;

				@Comment({"The pitch turn speed of the Mortar (in degrees)."})
				@RequiresMcRestart
				public static float pitchSpeed = 1f;
			}

			public static class EmplacementWeapons
			{

				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.autocannon")
				@Comment("Config for the Autocannon Emplacement, allows for changes to fire rate, energy consumption, movement speed, health and detection radius")
				public static Autocannon autocannon;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.machinegun")
				@Comment("Config for the Machinegun Emplacement, allows for changes to fire rate, energy consumption, movement speed, health and detection radius")
				public static Machinegun machinegun;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.tesla")
				@Comment("Config for the Teslacoil Emplacement, allows for changes to fire rate, energy consumption, health and detection radius")
				public static TeslaCoil teslaCoil;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.infrared_observer")
				@Comment("Config for the Infrared Observer Emplacement, allows for changes to energy consumption, movement speed, health and detection radius")
				public static InfraredObserver infraredObserver;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.cpds")
				@Comment("Config for the CPDS Emplacement, allows for changes to fire rate, energy consumption, movement speed, health and detection radius")
				public static CPDS cpds;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.heavy_chemthrower")
				@Comment("Config for the Heavy Chemthrower Emplacement, allows for changes to fire rate, energy consumption, movement speed, health and detection radius")
				public static HeavyChemthrower heavyChemthrower;
				@SubConfig
				@LangKey("machineupgrade.immersiveintelligence.heavy_railgun")
				@Comment("Config for the Heavy Railgun Emplacement, allows for changes to fire rate, energy consumption, movement speed, health and detection radius")
				public static HeavyRailgun heavyRailgun;


				public static class Autocannon
				{
					@Comment({"Yaw rotation speed (degrees/tick)"})
					public static float yawRotateSpeed = 4;

					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 4;

					@Comment({"Time required to reload all the magazines."})
					public static int reloadTime = 280;

					@Comment({"Time required to fire a single bullet."})
					public static int bulletFireTime = 3;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 200;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 32;

					@Comment({"Enemy detection range (in blocks)"})
					public static float attackRadius = 40;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 2048;
				}

				public static class Machinegun
				{
					@Comment({"Yaw rotation speed (degrees/tick)"})
					public static float yawRotateSpeed = 4;

					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 4;

					@Comment({"Time required to reload all the magazines."})
					public static int reloadTime = 200;

					@Comment({"Time required to fire a single bullet."})
					public static int bulletFireTime = 2;

					@Comment({"Time required for machinegun nest setup (barrel attachment animation) (in ticks)"})
					public static int setupTime = 150;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 150;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 24;

					@Comment({"Enemy attack range (in blocks)"})
					public static float attackRadius = 32;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 1024;
				}

				public static class TeslaCoil
				{
					@Comment({" \"reload\" time after dealing damage (in ticks)."})
					public static int damageDelay = 10;

					@Comment({"Damage dealt to enemies (in half-hearts)."})
					public static int damage = 10;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 3096;

					@Comment({"Energy used per shot (in IF)"})
					public static int energyUsage = 2048;

					@Comment({"Energy stored inside the weapon platform (in IF)"})
					public static int energyStorage = 32000000;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 200;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 16;

					@Comment({"Enemy attack range (in blocks)"})
					public static float attackRadius = 16;
				}

				public static class InfraredObserver
				{
					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 2;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 100;

					@Comment({"Time required for observer setup (lens attachment animation) (in ticks)."})
					public static int setupTime = 300;

					//3.5 chunks
					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 56;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 1024;
				}

				public static class CPDS
				{
					@Comment({"Yaw rotation speed (degrees/tick)"})
					public static float yawRotateSpeed = 8;

					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 8;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 350;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 24;

					@Comment({"Enemy attack range (in blocks)"})
					public static float attackRadius = 48;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 4096;

					@Comment({"Time required to reload the magazine."})
					public static int reloadTime = 120;
				}

				public static class HeavyChemthrower
				{
					@Comment({"Time required for chemthrower setup (barrel extension animation) (in ticks)."})
					public static int setupTime = 100;

					@Comment({"Fluid tank capacity of the heavy chemthrower (in mB)."})
					public static int tankCapacity = 8000;

					@Comment({"Yaw rotation speed (degrees/tick)"})
					public static float yawRotateSpeed = 2;

					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 1;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 120;

					@Comment({"Time required to fire a single chemthrower particle (in ticks)."})
					public static int sprayTime = 0;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 16;

					@Comment({"Enemy attack range (in blocks)"})
					public static float attackRadius = 32;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 2048;
				}

				public static class HeavyRailgun
				{
					@Comment({"Time required to fire a single shot."})
					public static int shotFireTime = 40;

					@Comment({"Time required for loading a single projectile."})
					public static int reloadTime = 20;

					@Comment({"Time required for setting up the emplacement."})
					public static int setupTime = 100;

					@Comment({"Starting/max health of the turret (in half-hearts)"})
					public static int maxHealth = 350;

					@Comment({"Yaw rotation speed (degrees/tick)"})
					public static float yawRotateSpeed = 1.75f;

					@Comment({"Pitch rotation speed (degrees/tick)"})
					public static float pitchRotateSpeed = 0.65f;

					@Comment({"Enemy detection range (in blocks)"})
					public static float detectionRadius = 16;

					@Comment({"Enemy attack range (in blocks)"})
					public static float attackRadius = 64;

					@Comment({"Base energy usage per tick (in IF)."})
					public static int energyUpkeepCost = 2048;
				}
			}

			public static class Railgun
			{
				@Comment({"If disabled, II will not make any changes to IE railgun. This also disables using railgun grenades (as they use a custom entity)."})
				public static boolean enableRailgunOverride = true;

				@Comment({"Make standard railgun rods to be able to penetrate mobs (depending on metal)."})
				public static boolean enablePenetration = true;

				@Comment({"Whether the railgun has recoil (pushes the shooter to back, depending on projectile mass)."})
				public static boolean railgunRecoil = true;

				@Comment({"Whether the railgun can only be used when in mainhand."})
				public static boolean disableRailgunOffhand = true;
			}

			public static class Grenade
			{
				@Comment({
						"Changes looks of the grenades",
						"0 - new look",
						"1 - old look, but cores are colored",
						"2 - old look"
				})
				@RangeInt(min = 0, max = 2)
				public static int classicGrenades = 0;

				@Comment({"Grenade's initial speed modifier."})
				@RangeDouble(min = 0)
				public static float throwSpeedModifier = 1.65f;
			}

			public static class Mines
			{
				@Comment({
						"Changes color of the tripmine ",
						"0 - steel",
						"1 - green",
						"2 - dull-yellow (makes your tripmine a true S-Mine straight out of ze [REDACTED])"
				})
				@RangeInt(min = 0, max = 2)
				public static int tripmineColor = 0;

				@Comment({"Time before colision is being detected for navy mine after placing it (in ticks)"})
				public static int navalMineArmTime = 60;


				@Comment({"Energy capacity of radio explosives (in IF)."})
				public static int energyCapacity = 240000;

				@Comment({"Energy usage by radio explosives per tick (in IF)."})
				public static int energyUsage = 10;

				@Comment({"Radio signal range of the radio explosives (radius)."})
				public static int radioRange = 32;

				@RangeDouble(min = 0, max = 1)
				@Comment({"How much the range decreases when there is bad weather (rain, snow) ( 1 - full range, 0.5 - half range, 0 - no range, etc.)"})
				public static double weatherHarshness = 0.35;

				@Comment({"A list of all entities which will not activate the Tripmine"})
				public static String[] tripmineBlacklist = new String[]{
						"minecraft:chicken",
						"minecraft:rabbit",
						"immersiveintelligence:bullet",
						"immersiveintelligence:silverfish",
						"immersiveintelligence:endermite"
				};

			}

			public static class AmmoMagazines
			{
				@Comment({"Bullet capacity of the Machinegun magazine."})
				public static int machinegunCapacity = 48;
				@Comment({"Time required to load a single bullet into the Machinegun magazine (in ticks)."})
				public static int machinegunReloadTime = 20;

				@Comment({"Bullet capacity of the Submachinegun magazine."})
				public static int submachinegunCapacity = 24;
				@Comment({"Time required to load a single bullet into the Submachinegun magazine (in ticks)."})
				public static int submachinegunReloadTime = 20;

				@Comment({"Bullet capacity of the Rifle magazine."})
				public static int rifleCapacity = 12;
				@Comment({"Time required to load a single bullet into the Rifle magazine (in ticks)."})
				public static int rifleReloadTime = 20;

				@Comment({"Bullet capacity of the Submachinegun drum magazine."})
				public static int submachinegunDrumCapacity = 64;
				@Comment({"Time required to load a single bullet into the Submachinegun drum (in ticks)."})
				public static int submachinegunDrumReloadTime = 20;

				@Comment({"Bullet capacity of the Assault Rifle magazine."})
				public static int assaultRifleCapacity = 32;
				@Comment({"Time required to load a single bullet into the Assault Rifle magazine (in ticks)."})
				public static int assaultRifleReloadTime = 20;

				@Comment({"Bullet capacity of the Autocannon magazine."})
				public static int autocannonCapacity = 16;
				@Comment({"Time required to load a single shell into the Autocannon (in ticks)."})
				public static int autocannonReloadTime = 20;

				@Comment({"Bullet capacity of the CPDS drum magazine."})
				public static int cpdsDrumCapacity = 128;
				@Comment({"Time required to load a single bullet into the CPDS drum (in ticks)."})
				public static int cpdsDrumReloadTime = 20;

				@Comment({"Bullet capacity of the Pistol magazine."})
				public static int pistolCapacity = 16;
				@Comment({"Time required to load a single bullet into the Pistol magazine (in ticks)."})
				public static int pistolReloadTime = 20;
			}

			public static class Rifle
			{
				@Comment({"Time required to reload a stick magazine in SMG. (in ticks)"})
				public static int bulletReloadTime = 20;

				@Comment({"Time required to reload a drum magazine in SMG. (in ticks)"})
				public static int magazineReloadTime = 65;

				@Comment({"Time required to aim the SMG. (in ticks)"})
				public static int clipSize = 4;

				@Comment({"Time required to aim the SMG. (in ticks)"})
				public static int aimTime = 15;

				@Comment({"Time required to fire a single bullet."})
				public static int bulletFireTime = 20;

				@Comment({"Time required to fire a single bullet."})
				public static int bulletFireTimeSemiAuto = 10;

				@Comment({"Maximum amount of horizontal recoil."})
				public static float longBarrelVelocityMod = 2.25f;

				@Comment({"Amount of horizontal recoil after taking a shot."})
				public static float recoilHorizontal = 0.5f;

				@Comment({"Amount of vertical recoil after taking a shot."})
				public static float recoilVertical = 2.75f;

				@Comment({"Maximum amount of horizontal recoil."})
				public static float maxRecoilHorizontal = 3.5f;

				@Comment({"Maximum amount of vertical recoil."})
				public static float maxRecoilVertical = 12f;

				@Comment({"Amount of vertical recoil after taking a shot."})
				public static float recoilSemiAutoVertical = 1f;

				@Comment({"Range in which enemies will be attracted to the gunshot."})
				public static int enemyAttractRange = 32;
			}

			public static class Submachinegun
			{
				@Comment({"Time required to reload a stick magazine in SMG. (in ticks)"})
				public static int clipReloadTime = 45;

				@Comment({"Time required to reload a drum magazine in SMG. (in ticks)"})
				public static int drumReloadTime = 80;

				@Comment({"Time required to aim the SMG. (in ticks)"})
				public static int aimTime = 10;

				@Comment({"Time required to aim the SMG with folded stock upgrade."})
				public static int aimTimeFoldedStock = 4;

				@Comment({"Time required to fire a single bullet."})
				public static int bulletFireTime = 2;

				@Comment({"Maximum amount of horizontal recoil."})
				public static float sturdyBarrelVelocityMod = 1.25f;

				//some people are able to report "bugs", yet unable to reset a config file when updating versions
				@Comment({"Amount of horizontal recoil after taking a shot."})
				public static float newRecoilHorizontal = 0.345f;

				@Comment({"Amount of vertical recoil after taking a shot."})
				public static float newRecoilVertical = 0.625f;

				@Comment({"Maximum amount of horizontal recoil."})
				public static float newMaxRecoilHorizontal = 14.5f;

				@Comment({"Maximum amount of vertical recoil."})
				public static float newMaxRecoilVertical = 9f;

				@Comment({"Range in which enemies will be attracted to the gunshot."})
				public static int enemyAttractRange = 36;

				@Comment({"Range in which enemies will be attracted to the gunshot for a suppressed SMG."})
				public static int enemyAttractRangeSuppressor = 6;
			}

			public static class AssaultRifle
			{
				//--- Stock ---//

				@Comment({"Time required to reload a magazine in AR. (in ticks)"})
				public static int clipReloadTime = 45;

				@Comment({"Time required to aim the AR. (in ticks)"})
				public static int aimTime = 15;

				@Comment({"Time required to fire a single bullet in Auto mode."})
				public static int bulletFireTime = 2;

				@Comment({"Amount of horizontal recoil after taking a shot."})
				public static float recoilHorizontal = 0.345f;

				@Comment({"Amount of vertical recoil after taking a shot."})
				public static float recoilVertical = 0.425f;

				@Comment({"Maximum amount of horizontal recoil."})
				public static float maxRecoilHorizontal = 8.5f;

				@Comment({"Maximum amount of vertical recoil."})
				public static float maxRecoilVertical = 8.5f;

				@Comment({"Range in which enemies will be attracted to the gunshot."})
				public static int enemyAttractRange = 36;

				//--- Upgrades ---//

				@Comment({"Time required to load a railgun grenade to an upgraded AR. (in ticks)"})
				public static int grenadeReloadTime = 80;

				@Comment({"Time required to fire a railgun grenade in AR with the upgrade. (in ticks)"})
				public static int grenadeFireTime = 40;

				@Comment({"Energy used per tick by the Infrared Scope upgrade."})
				public static int upgradeIRScopeEnergy = 20;

				@Comment({"Energy used per shot by the Electric Firing Motor upgrade."})
				public static int upgradeFiringMotorEnergy = 10;

				@Comment({"Time required to fire the AR in semi-auto mode with the railgun chamber upgrade"})
				public static int upgradeRailgunChamberFireTime = 4;

				@Comment({"Energy used per shot by the Railgun Chamber upgrade."})
				public static int upgradeRailgunChamberEnergy = 40;

				@Comment({"Energy used per tick by the Gyroscopic Stabilizer upgrade."})
				public static int upgradeStabilizerEnergy = 10;

				@Comment({"Energy used per tick by the Stereoscopic Rangefinder upgrade."})
				public static int upgradeRangefinderEnergy = 1024;
			}

			public static class Machinegun
			{
				@Comment({"Time required to reload a clip in MG."})
				public static int clipReloadTime = 35;

				@Comment({"Time required to fire a single bullet in MG."})
				public static int fireDelay = 2;

				@Comment({"Time required to set up the MG (in ticks)."})
				public static int setupTime = 50;

				@Comment({"Max scatter of heat, higher values will force the player to wait until the gun cools down."})
				public static int maxOverheat = 250;

				@Comment({"Amount of horizontal recoil after taking a shot."})
				public static float recoilHorizontal = 2.5f;

				@Comment({"Amount of vertical recoil after taking a shot."})
				public static float recoilVertical = 2.5f;

				//Upgrades

				@Comment({"Fire rate multiplier when heavy barrel is mouted on mg."})
				public static int heavyBarrelFireDelay = 1;

				@Comment({"Horizontal recoil after taking a shot with heavy barrel mounted."})
				public static float recoilHBHorizontal = 1.25f;

				@Comment({"Vertical recoil after taking a shot with heavy barrel mounted."})
				public static float recoilHBVertical = 1.25f;

				@Comment({"Water usage when water cooling upgrade is mounted on mg (in mB)."})
				public static int waterCoolingFluidUsage = 10;

				@RequiresMcRestart
				@Comment({"Coolant tank capacity of the water cooling upgrade."})
				public static int waterCoolingTankCapacity = 4000;

				@Comment({"Setup time multiplier when the mg is mounted on a tripod."})
				public static float tripodSetupTimeMultiplier = 2.5f;

				@Comment({"Recoil multiplier when the mg is mounted on a tripod."})
				public static float tripodRecoilMultiplier = 0.125f;

				@Comment({"Setup time multiplier when the precise bipod is mouted on mg."})
				public static float preciseBipodSetupTimeMultiplier = 1.5f;

				@Comment({"Recoil multiplier when the precise bipod is mouted on mg."})
				public static float preciseBipodRecoilMultiplier = 0.25f;

				@Comment({"Setup time multiplier when the hasty bipod is mouted on mg."})
				public static float hastyBipodSetupTimeMultiplier = 0.5f;

				@Comment({"Recoil multiplier when the hasty bipod is mouted on mg."})
				public static float hastyBipodRecoilMultiplier = 1.5f;

				@Comment({"Horizontal recoil multiplier when the double magazine upgrade is mouted on mg."})
				public static float recoilSecondMagazine = 1.65f;

				@Comment({"Setup time multiplier when the belt fed loader upgrade is mouted on mg."})
				public static float beltFedLoaderSetupTimeMultiplier = 0.5f;

				@Comment({"Infrared scope energy usage per tick"})
				public static int infraredScopeEnergyUsage = 15;

				@Comment({"Max zoom of a machinegun with a scope mounted (in Blu's Unit of Distance Measurement™)."})
				@RequiresMcRestart
				public static float[] machinegunScopeMaxZoom = new float[]{0.55f, 0.35f, 0.15f};

				@Comment({"Shield's initial strength (resistance vs attacks)."})
				public static int shieldStrengthInitial = 45;

				@Comment({"Setup time multiplier when a shield is mouted on mg."})
				public static float shieldSetupTimeMultiplier = 0.5f;

			}
		}

		public static class Ammunition
		{
			@Comment({"Whether explosive ammo components can break blocks"})
			public static boolean blockDamage = true;

			@Comment({"Default velocity of a mortar shell."})
			public static float mortarVelocity = 8f*0.7f;

			@Comment({"Default velocity of a light howitzer shell."})
			public static float lightHowiVelocity = 10f*0.7f;

			@Comment({"Default velocity of an artillery howitzer shell."})
			public static float artilleryHowiVelocity = 70f*0.7f;

			@Comment({"Default velocity of a railgun grenade."})
			public static float railgunGrenadeVelocity = 5f*0.7f;

			@Comment({"Default velocity of a thrown grenade."})
			public static float grenadeVelocity = 1f;

			@Comment({"Default velocity of a machinegun bullet."})
			public static float autocannonVelocity = 6f*0.7f;

			@Comment({"Default velocity of a machinegun bullet."})
			public static float mgVelocity = 6.5f*0.7f;

			@Comment({"Default velocity of a submachinegun bullet."})
			public static float smgVelocity = 5f*0.7f;

			@Comment({"Default velocity of an assault rifle bullet."})
			public static float stgVelocity = 6.5f*0.7f;

			@Comment({"Default velocity of a revolver cartridge."})
			public static float revolverVelocity = 6f*0.7f;
		}

		public static class Wires
		{
			@Comment({"The RGB color of the data wire."})
			public static int dataWireColouration = 0xb3d1d6;

			@Comment({"The maximum length of a single data wire."})
			public static int dataWireLength = 24;

			@Comment({"The RGB color of the small data wire."})
			public static int smallRedstoneWireColouration = 0xff2f2f;

			@Comment({"The maximum length of a single small data wire. Should not be much."})
			public static int smallRedstoneWireLength = 4;

			@Comment({"The RGB color of the small data wire."})
			public static int smallDataWireColouration = 0xb3d1d6;

			@Comment({"The maximum length of a single small data wire. Should not be much."})
			public static int smallDataWireLength = 4;

			@Comment({"The RGB color of the data wire."})
			public static int tripwireColouration = 0x967e6d;

			@Comment({"The maximum length of the tripwire. Should be medium range at best."})
			public static int tripwireLength = 8;
		}

		public static class Vehicles
		{
			@SubConfig
			@LangKey("entity.motorbike.name")
			@Comment("Config for the motorbike, allows for changes in durability, fuel usage and capacity")
			public static Motorbike motorbike;

			@LangKey("entity.field_howitzer.name")
			@SubConfig
			@Comment("Config for the Field Howitzer, allows for changes to durability and fire rate")
			public static FieldHowitzer fieldHowitzer;

			@Comment({"When enabled, clutch will not be engaged automatically during gear shift by its own."})
			public static boolean manualClutch = false;

			@Comment({"When disabled, gearbox will shift gears automatically based on speed."})
			public static boolean manualGearbox = true;


			public static class Motorbike
			{

				@Comment({"Fuel capacity of the motorbike."})
				public static int fuelCapacity = 12000;

				@Comment({"Fuel usage per one meter driven."})
				public static int fuelUsage = 6;

				@Comment({"Damage resistance of the wheels."})
				public static int wheelDurability = 40;

				@Comment({"Damage resistance of the engine."})
				public static int engineDurability = 100;

				@Comment({"Damage resistance of the fuel tank."})
				public static int fuelTankDurability = 80;

				@Comment({"Amount of fuel burn per time, dependent on diesel generator fluids (in mB)"})
				public static int fuelBurnAmount = 8;

			}

			public static class FieldHowitzer
			{
				@Comment({"Damage resistance of the wheels."})
				public static int wheelDurability = 40;

				@Comment({"Damage resistance of the gun frame."})
				public static int mainDurability = 160;

				@Comment({"Damage resistance of the gun barrel."})
				public static int gunDurability = 80;

				@Comment({"Damage resistance of the gun shield (both sides have common health)."})
				public static int shieldDurability = 160;

				@Comment({"Time required to tow a field howitzer."})
				public static int towingTime = 80;

				@Comment({"Time required to set up field howitzer after moving it."})
				public static int setupTime = 15;

				@Comment({"Time required to reload a field howitzer."})
				public static int reloadTime = 80;

				@Comment({"Time required to fire a single shell using the field howitzer."})
				public static int fireTime = 50;
			}
		}

		public static class Factions
		{
			@RequiresMcRestart
			@Comment({"Allows to disable II's faction system completely. Chunk claiming, ownership and commanding Hanses will not work when disabled."})
			public static boolean enableFactions = true;

			@RequiresMcRestart
			@Comment({"When enabled, players not belonging to a faction cannot access containers on chunks belonging to other factions."})
			public static boolean preventContainerAccess = true;

			@RequiresMcRestart
			@Comment({"Determines how often faction property-bound chunkloader tickets are checked for validity. (in ticks)"})
			public static int chunkloaderTickDelay = 200;

			@RequiresMcRestart
			@Comment({"Determines how often properties try to claim surrounding chunks. (in ticks)"})
			public static int claimTickDelay = 200;
		}

		public static class MechanicalDevices
		{
			@Comment({"The modifier of internal torque of a machine using this gear.", GEARS})
			public static float[] gearTorqueModifier = new float[]{0.25f, 0.5f, 1f, 2f, 4f};

			@Comment({"Belts will break if Torque is higher than this value.", BELTS})
			public static int[] beltMaxTorque = new int[]{50, 200, 100};

			@Comment({"Torque loss, later multiplied by belt length.", BELTS})
			public static float[] beltTorqueLoss = new float[]{0.05f, 0.1f, 0.01f};

			@Comment({"Max length of the belt, works exactly like wires (measured in blocks).", BELTS})
			public static int[] beltLength = new int[]{8, 16, 16};

			@Comment({"Immersive Flux to Rotary Flux conversion ratio (default 4 RoF = 1 IF)."})
			public static float rofConversionRatio = 4f;

			@Comment({"Default torque, used as a fallback, when IE rotational device is not recognised."})
			public static float dynamoDefaultTorque = 16f;

			@Comment({"Torque multiplier for the windmill."})
			public static float dynamoWindmillTorque = 20f;

			@Comment({"Torque multiplier for the windmill."})
			public static float dynamoWatermillTorque = 24f;

			@Comment({"Torque multiplier for the axle from MysticalMechanics."})
			public static float dynamoMMAxleTorque = 18f;

			@Comment({"Torque multiplier for the axle from MysticalMechanics."})
			public static float dynamoBWMAxleTorque = 18f;
		}
	}
}
