package pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.part;

import net.minecraft.entity.Entity;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.Vec3d;
import pl.pabilo8.immersiveintelligence.api.rotary.IRotaryEnergy;
import pl.pabilo8.immersiveintelligence.api.utils.vehicles.IVehicleMultiPart;
import pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.VehicleBlueprint;
import pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.VehicleDurability;
import pl.pabilo8.immersiveintelligence.common.util.IIMath;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.List;

/**
 * Represents a wheel entity for vehicles with advanced physics including suspension,
 * climbing capabilities, and force calculation. Each wheel operates independently
 * but contributes to overall vehicle movement.
 *
 * @author Pabilo8 (pabilo@iiteam.net)
 * @updated 29.09.2025
 * @since 13.07.2020
 */
public class EntityVehicleWheel<T extends Entity & IVehicleMultiPart<T>> extends EntityVehiclePart<T> implements IRotaryEnergy
{
	//--- Controls ---//
	/**
	 * Whether this wheel receives power from the engine, can be steered, or just follows the drivetrain.
	 */
	private WheelType type;
	/**
	 * Power factor -1 to 1
	 */
	private float powerFactor = 0;
	/**
	 * Braking factor 0-1
	 */
	private float brakeFactor = 0;
	/**
	 * Efficiency factor 0-1, depends on damage of the tire
	 */
	private float efficiencyModifier = 1f;
	/**
	 * Designated steering angle, when the wheel is steerable
	 */
	private float steeringAngle = 0.0f;

	//--- Animation ---//
	/**
	 * Distance this wheel has already traversed in blocks, for rendering purposes
	 */
	private float wheelTraverse = 0;
	/**
	 * Current compression for this wheel's suspension, in blocks, used for rendering purposes
	 */
	private double suspensionCompression = 0.0;
	/**
	 * Previous tick's compression for this wheel's suspension, used for interpolation during render
	 */
	private double lastSuspensionCompression = 0.0;
	/**
	 * Max compression for this wheel's suspension, in blocks
	 */
	private double maxSuspensionCompression = 1.0;
	/**
	 * Weight share of the vehicle's total mass that this wheel carries
	 */
	private double weightShare = 1.0;

	//--- Climbing ---//
	/**
	 * Max wall height this wheel can climb in blocks
	 */
	private double maxClimbHeight = 1.125;
	/**
	 * Climbing height per tick
	 */
	private double climbPerTick = 0.125;
	/**
	 * Current climb height, grows when climbing until it hits maxClimbHeight
	 */
	private float currentClimbOffset = 0f;

	//--- Last Computed Outputs ---//
	private WheelForces lastForces = new WheelForces(Vec3d.ZERO, 0, false);

	/**
	 * Constructs a new vehicle wheel entity.
	 *
	 * @param parentExt the parent vehicle entity
	 * @param name      the name of this wheel part
	 * @param offset    the offset from vehicle center
	 * @param aabb      the bounding box for collision
	 */
	public EntityVehicleWheel(T parentExt, String name, Vec3d offset, AxisAlignedBB aabb)
	{
		super(parentExt, name, offset, aabb);
		this.type = WheelType.IDLER;
	}

	/**
	 * Configures the wheel's control capabilities.
	 *
	 * @return this wheel for method chaining
	 */
	public EntityVehicleWheel<T> withType(WheelType type)
	{
		this.type = type;
		return this;
	}

	/**
	 * Configures the wheel's climbing capabilities.
	 *
	 * @param maxClimbHeight maximum height the wheel can climb in blocks
	 * @param climbPerTick   climbing speed per tick
	 * @return this wheel for method chaining
	 */
	public EntityVehicleWheel<T> withClimbingAbilities(double maxClimbHeight, double climbPerTick)
	{
		this.maxClimbHeight = maxClimbHeight;
		this.climbPerTick = climbPerTick;
		return this;
	}

	/**
	 * Configures the wheel's suspension properties
	 *
	 * @param maxCompression maximum compression in blocks
	 * @return this wheel for method chaining
	 */
	public EntityVehicleWheel<T> withSuspension(double maxCompression)
	{
		this.maxSuspensionCompression = maxCompression;
		return this;
	}

	public EntityVehicleWheel<T> withWeightShare(double weightShare)
	{
		this.weightShare = weightShare;
		return this;
	}

	@Override
	public EntityVehicleWheel<T> withHitbox(@Nonnull VehicleDurability hitbox)
	{
		super.withHitbox(hitbox);
		return this;
	}

	//--- Enhanced Force Calculation ---

	/**
	 * Calculates the forces and torque generated by this wheel using enhanced friction model.
	 */
	public WheelForces calculateForces()
	{
		if(parentExt==null)
			return this.lastForces = new WheelForces(Vec3d.ZERO, 0.0, false);
		VehicleBlueprint blueprint = parentExt.getVehicleBlueprint();

		//Ground detection
		boolean grounded = checkForGround();

		//Calculate efficiency modifier and drive force
		this.efficiencyModifier = this.durability==null?1f: this.durability.getDamageFactor() > 0.3?1f: 0.15f;
		double driveForce = this.powerFactor*(1f-brakeFactor)*efficiencyModifier;
		double angularVel = this.parentExt.getAngularVelocity();

		//Wheel position in world coordinates
		Vec3d wheelPos = parentExt.getPositionVector().add(IIMath.offsetPosDirectionXYZ(offset, parentExt.rotationYaw, parentExt.rotationPitch, 0));

		//Wheel orientation in the world
		double wheelAngle = Math.toRadians(MathHelper.wrapDegrees(parentExt.rotationYaw+this.steeringAngle));

		//Forward direction is (sinA, cosA) which is (-sin(wheelAngle), cos(wheelAngle))
		//Lateral (right) direction is (cosA, -sinA) which is (cos(wheelAngle), sin(wheelAngle))
		double sinA = -MathHelper.sin((float)wheelAngle);
		double cosA = MathHelper.cos((float)wheelAngle);

		//Velocity at wheel position
		double relX = wheelPos.x-parentExt.posX;
		double relZ = wheelPos.z-parentExt.posZ;
		Vec3d velocity = parentExt.getVelocity();
		//Rotational velocity components
		double wheelVx = velocity.x-angularVel*relZ;
		double wheelVz = velocity.z+angularVel*relX;

		//Project velocity onto wheel axes
		double vLat = wheelVx*cosA-wheelVz*sinA;

		//Lateral friction (all wheels)
		double latFrictionCoef = this.type.isDriven()?blueprint.lateralFrictionDrive(): blueprint.lateralFrictionIdler();
		//Additional steering friction
		if(Math.abs(this.steeringAngle) > 0.1f)
			latFrictionCoef *= blueprint.steeringFrictionMultiplier();
		double latFriction = -vLat*latFrictionCoef;

		//Total force in wheel's local axes
		double fx = driveForce*sinA+latFriction*cosA;
		double fz = driveForce*cosA-latFriction*sinA;

		//Compile and return forces
		Vec3d force = new Vec3d(fx*blueprint.forceFactor()*2, 0, fz*blueprint.forceFactor()*2);
		double torque = (relX*fz-relZ*fx)*blueprint.torqueFactor();
		addWheelTraverse((float)force.lengthVector());
		return this.lastForces = new WheelForces(force, torque, grounded);
	}

	/**
	 * Precision ground detection based on the wheel's AABB.
	 * Returns true if the wheel is touching or nearly touching any solid block underneath.
	 */
	private boolean checkForGround()
	{
		// Get wheel world-space bounding box
		AxisAlignedBB bb = aabb.offset(this.posX, this.posY, this.posZ);

		// Expand downward by a small epsilon to catch "almost touching" situations
		final double epsilon = 0.05;
		AxisAlignedBB probeBB = bb.offset(0, -epsilon, 0);

		// Query collisions with blocks only (exactly like move logic)
		List<AxisAlignedBB> collisions = world.getCollisionBoxes(null, probeBB);

		return !collisions.isEmpty();
	}


	//--- Suspension ---//

	/**
	 * Calculates the suspension compression for rendering with smooth interpolation
	 * This only calculates the value, does not set it
	 *
	 * @param partialTicks partial tick time for interpolation
	 * @return interpolated suspension compression value
	 */
	public double calculateSuspensionCompression(float partialTicks)
	{
		return this.lastSuspensionCompression+(this.suspensionCompression-this.lastSuspensionCompression)*partialTicks;
	}

	/**
	 * Simulates suspension compression based on vehicle state and stores the result
	 * Call this each tick during vehicle update
	 */
	public void simulateSuspensionCompression()
	{
		//Store previous value for interpolation
		this.lastSuspensionCompression = this.suspensionCompression;
		boolean grounded = checkForGround();
		double newCompression;

		//No compression when in air
		if(grounded)
		{
			//Base compression when on ground
			newCompression = 0.2;
			//Add compression from vertical impacts (falling, bumps)
			double verticalImpact = calculateVerticalImpact();
			newCompression += verticalImpact;

			//Small oscillation during movement
			if(parentExt!=null)
			{
				double speed = Math.sqrt(parentExt.motionX*parentExt.motionX+parentExt.motionZ*parentExt.motionZ);
				if(speed > 0.1)
				{
					double oscillation = Math.sin(world.getTotalWorldTime()*0.3+this.hashCode()*0.1)*0.05;
					newCompression += Math.abs(oscillation);
				}
			}
		}
		else
			newCompression = 0.0;

		//Smoothly transition to new compression value
		double smoothing = 0.4; //Higher = faster response
		this.suspensionCompression += (newCompression-this.suspensionCompression)*smoothing;
		//Clamp to valid range
		this.suspensionCompression = MathHelper.clamp(this.suspensionCompression, 0.0, maxSuspensionCompression);
		//Update last Y position for next tick's impact calculation
		this.prevPosY = this.posY;
	}

	/**
	 * Calculates compression from vertical impacts (falling, hitting bumps)
	 */
	private double calculateVerticalImpact()
	{
		if(parentExt==null)
			return 0.0;
		double impact = 0.0;

		//Detect rapid downward movement (falling or hitting bumps)
		double verticalVelocity = this.prevPosY-this.posY; //Positive = moving downward
		//Scale impact by velocity squared (like kinetic energy)
		if(verticalVelocity > 0.05)
			impact = Math.min(verticalVelocity*verticalVelocity*10.0, 0.3);

		return impact;
	}

	//--- Control Methods ---

	/**
	 * Sets the steering angle for steerable wheels.
	 *
	 * @param angle the desired steering angle in degrees
	 */
	public void setSteeringAngle(float angle)
	{
		if(this.type.isSteerable())
			this.steeringAngle = MathHelper.clamp(angle, -45.0f, 45.0f);
	}

	//--- Public Moving Methods ---

	/**
	 * Sets the movement control factors for this wheel.
	 *
	 * @param powerFactor the power factor (0..1) for driving force
	 * @param brakeFactor the brake factor (0..1) for braking force
	 */
	public void setMovementFactors(float powerFactor, float brakeFactor)
	{
		this.powerFactor = powerFactor;
		this.brakeFactor = brakeFactor;
	}

	/**
	 * Updates wheel rotation and traverse for visual effects.
	 *
	 * @param distance how much has the wheel moved
	 */
	public void addWheelTraverse(float distance)
	{
		this.wheelTraverse += distance*(float)getWheelRadius()*90f;
	}

	//--- Properties ---

	public WheelType getType()
	{
		return type;
	}

	public float getSteeringAngle()
	{
		return this.steeringAngle;
	}

	public WheelForces getLastForces()
	{
		return lastForces;
	}

	public float getWheelTraverse()
	{
		return wheelTraverse;
	}

	public float getPowerFactor()
	{
		return powerFactor;
	}

	public float getBrakeFactor()
	{
		return brakeFactor;
	}

	public float getEfficiencyModifier()
	{
		return efficiencyModifier;
	}

	public double getMaxClimbHeight()
	{
		return maxClimbHeight;
	}

	public double getClimbPerTick()
	{
		return climbPerTick;
	}

	public float getCurrentClimbOffset()
	{
		return currentClimbOffset;
	}

	public double getWheelRadius()
	{
		return height/2;
	}

	//--- IRotaryEnergy ---//

	@Override
	public float getTorque()
	{
		return 0;
	}

	@Override
	public void setTorque(float torque)
	{

	}

	@Override
	public float getRotationSpeed()
	{
		return 0;
	}

	@Override
	public void setRotationSpeed(float speed)
	{

	}

	@Override
	public RotationSide getSide(@Nullable EnumFacing facing)
	{
		return null;
	}
}
