package pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.part;

import net.minecraft.entity.Entity;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.MathHelper;
import net.minecraft.util.math.Vec3d;
import pl.pabilo8.immersiveintelligence.api.rotary.IRotaryEnergy;
import pl.pabilo8.immersiveintelligence.api.utils.vehicles.IVehicleMultiPart;
import pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.VehicleBlueprint;
import pl.pabilo8.immersiveintelligence.common.entity.vehicle.utils.VehicleDurability;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Represents a wheel entity for vehicles with advanced physics including suspension,
 * climbing capabilities, and force calculation. Each wheel operates independently
 * but contributes to overall vehicle movement.
 *
 * @author Pabilo8 (pabilo@iiteam.net)
 * @updated 29.09.2025
 * @since 13.07.2020
 */
public class EntityVehicleWheel<T extends Entity & IVehicleMultiPart<T>> extends EntityVehiclePart<T> implements IRotaryEnergy
{
	//--- Controls ---//
	/**
	 * Whether this wheel receives power from the engine, can be steered, or just follows the drivetrain.
	 */
	private WheelType type;
	/**
	 * Power factor -1 to 1
	 */
	private float powerFactor = 0;
	/**
	 * Braking factor 0-1
	 */
	private float brakeFactor = 0;
	/**
	 * Efficiency factor 0-1, depends on damage of the tire
	 */
	private float efficiencyModifier = 1f;

	//--- Animation ---//
	/**
	 * Distance this wheel has already traversed in blocks, for rendering purposes
	 */
	private float wheelTraverse = 0;
	/**
	 * Current compression for this wheel's suspension, in blocks, used for rendering purposes
	 */
	private double suspensionCompression = 0.0;
	/**
	 * Previous tick's compression for this wheel's suspension, used for interpolation during render
	 */
	private double lastSuspensionCompression = 0.0;
	/**
	 * Max compression for this wheel's suspension, in blocks
	 */
	private double maxSuspensionCompression = 1.0;
	/**
	 * Designated steering angle, when the wheel is steerable
	 */
	private float steeringAngle = 0.0f;

	//--- Climbing ---//
	/**
	 * Max wall height this wheel can climb in blocks
	 */
	private double maxClimbHeight = 1.0;
	/**
	 * Climbing height per tick
	 */
	private double climbPerTick = 0.25;
	/**
	 * Current climb height, grows when climbing until it hits maxClimbHeight
	 */
	private float currentClimbOffset = 0f;

	//--- Last Computed Outputs ---//
	private WheelForces lastForces = new WheelForces(Vec3d.ZERO, 0, false);

	/**
	 * Constructs a new vehicle wheel entity.
	 *
	 * @param parentExt the parent vehicle entity
	 * @param name      the name of this wheel part
	 * @param offset    the offset from vehicle center
	 * @param aabb      the bounding box for collision
	 */
	public EntityVehicleWheel(T parentExt, String name, Vec3d offset, AxisAlignedBB aabb)
	{
		super(parentExt, name, offset, aabb);
		this.type = WheelType.IDLER;
	}

	/**
	 * Configures the wheel's control capabilities.
	 *
	 * @return this wheel for method chaining
	 */
	public EntityVehicleWheel<T> withType(WheelType type)
	{
		this.type = type;
		return this;
	}

	/**
	 * Configures the wheel's climbing capabilities.
	 *
	 * @param maxClimbHeight maximum height the wheel can climb in blocks
	 * @param climbPerTick   climbing speed per tick
	 * @return this wheel for method chaining
	 */
	public EntityVehicleWheel<T> withClimbingAbilities(double maxClimbHeight, double climbPerTick)
	{
		this.maxClimbHeight = maxClimbHeight;
		this.climbPerTick = climbPerTick;
		return this;
	}

	@Override
	public EntityVehicleWheel<T> withHitbox(@Nonnull VehicleDurability hitbox)
	{
		super.withHitbox(hitbox);
		return this;
	}

	//--- Enhanced Force Calculation ---

	/**
	 * Calculates the forces and torque generated by this wheel using the simulation's model.
	 * Projects vehicle velocity onto wheel axes, applies drive and lateral friction forces, and returns force/torque in X-Z plane.
	 *
	 * @return WheelForces containing the force vector and torque value
	 */
	public WheelForces calculateForces(double maxLateralForce)
	{
		if(parentExt==null)
			return this.lastForces = new WheelForces(Vec3d.ZERO, 0.0, false);
		VehicleBlueprint blueprint = parentExt.getVehicleBlueprint();

		//Ground detection
		boolean grounded = checkForGround();

		//Calculate efficiency modifier and drive force
		this.efficiencyModifier = this.durability==null?1f: (this.durability.getDamageFactor() > 0.3?1f: 0.5f);
		double driveForce = this.powerFactor*(1f-brakeFactor)*efficiencyModifier;
		double angularVel = this.parentExt.getAngularVelocity();
		float parentAngle = (float)Math.toRadians(MathHelper.wrapDegrees(parentExt.rotationYaw));

		//wheel position in world coordinates
		double worldWheelX = parentExt.posX+MathHelper.sin(parentAngle)*offset.z+MathHelper.cos(parentAngle)*offset.x;
		double worldWheelZ = parentExt.posZ+MathHelper.cos(parentAngle)*offset.z-MathHelper.sin(parentAngle)*offset.x;

		//wheel orientation in world
		double wheelAngle = Math.toRadians(MathHelper.wrapDegrees(parentExt.rotationYaw+this.steeringAngle));
		double sinA = MathHelper.sin((float)wheelAngle);
		double cosA = MathHelper.cos((float)wheelAngle);

		//velocity at wheel position (vehicle velocity + rotational component)
		double relX = worldWheelX-parentExt.posX;
		double relZ = worldWheelZ-parentExt.posZ;
		double wheelVz = (parentExt.motionZ-angularVel*relX);
		double wheelVx = (parentExt.motionX+angularVel*relZ);

		//project velocity onto wheel axes
		double vLat = -(wheelVz*sinA+wheelVx*cosA)*4;

		//lateral friction (all wheels)
		double latFrictionCoef = this.type.isDriven()?blueprint.lateralFrictionDrive(): blueprint.lateralFrictionIdler();
		double latFriction = -vLat*latFrictionCoef;

		//Clamp and normalize lateral friction
		if(latFriction > maxLateralForce)
			latFriction = maxLateralForce;
		if(latFriction < -maxLateralForce)
			latFriction = -maxLateralForce;

		//total force in wheel's local axes
		double fx = -sinA*driveForce-cosA*latFriction;
		double fz = cosA*driveForce-sinA*latFriction;
		Vec3d force = new Vec3d(fx*blueprint.forceFactor(), 0, fz*blueprint.forceFactor());
		double torque = (relX*fx-relZ*fz)*blueprint.torqueFactor();

		//Compile and return forces
		return this.lastForces = new WheelForces(force, torque, grounded);
	}

	/**
	 * Simple raycast based ground detection
	 */
	private boolean checkForGround()
	{
		return true;
	}

	//--- Enhanced Control Methods ---

	/**
	 * Sets the steering angle for steerable wheels.
	 *
	 * @param angle the desired steering angle in degrees
	 */
	public void setSteeringAngle(float angle)
	{
		if(this.type.isSteerable())
		{
			this.steeringAngle = MathHelper.clamp(angle, -45.0f, 45.0f);
		}
	}

	//--- Public Moving Methods ---

	/**
	 * Sets the movement control factors for this wheel.
	 *
	 * @param powerFactor the power factor (0..1) for driving force
	 * @param brakeFactor the brake factor (0..1) for braking force
	 */
	public void setMovementFactors(float powerFactor, float brakeFactor)
	{
		this.powerFactor = powerFactor;
		this.brakeFactor = brakeFactor;
	}

	/**
	 * Updates wheel rotation and traverse for visual effects.
	 *
	 * @param distance how much has the wheel moved
	 */
	public void addWheelTraverse(float distance)
	{
		this.wheelTraverse += distance*2f;
	}

	//--- Properties ---

	public WheelType getType()
	{
		return type;
	}

	/**
	 * @return true if the wheel is currently grounded
	 */
	public boolean isGrounded()
	{
		return this.lastForces.isGrounded;
	}

	public Vec3d getLastForce()
	{
		return this.lastForces.force;
	}

	public double getLastYawTorque()
	{
		return this.lastForces.torque;
	}

	/**
	 * @return the current suspension compression amount
	 */
	public double getSuspensionCompressionPercentage()
	{
		return this.suspensionCompression/this.maxSuspensionCompression;
	}

	/**
	 * @return the current steering angle for steerable wheels
	 */
	public float getSteeringAngle()
	{
		return this.steeringAngle;
	}

	public float getWheelTraverse()
	{
		return wheelTraverse;
	}

	public float getPowerFactor()
	{
		return powerFactor;
	}

	public float getBrakeFactor()
	{
		return brakeFactor;
	}

	public float getEfficiencyModifier()
	{
		return efficiencyModifier;
	}

	public double getMaxClimbHeight()
	{
		return maxClimbHeight;
	}

	public double getClimbPerTick()
	{
		return climbPerTick;
	}

	public float getCurrentClimbOffset()
	{
		return currentClimbOffset;
	}

	public double getWheelRadius()
	{
		return height/2;
	}

	//--- IRotaryEnergy ---//

	@Override
	public float getTorque()
	{
		return 0;
	}

	@Override
	public void setTorque(float torque)
	{

	}

	@Override
	public float getRotationSpeed()
	{
		return 0;
	}

	@Override
	public void setRotationSpeed(float speed)
	{

	}

	@Override
	public RotationSide getSide(@Nullable EnumFacing facing)
	{
		return null;
	}

	public enum WheelType
	{
		STEERABLE,
		DRIVE,
		STEERABLE_DRIVE,
		IDLER;

		public boolean isDriven()
		{
			return this==DRIVE||this==STEERABLE_DRIVE;
		}

		public boolean isSteerable()
		{
			return this==STEERABLE||this==STEERABLE_DRIVE;
		}
	}

	/**
	 * Helper class for storing wheel force calculations.
	 * Contains both linear force vector and rotational torque.
	 */
	public static class WheelForces
	{
		public final Vec3d force;
		public final double torque;
		public final boolean isGrounded;

		public WheelForces(Vec3d force, double torque, boolean isGrounded)
		{
			this.force = force;
			this.torque = torque;
			this.isGrounded = isGrounded;
		}
	}
}
